NoticeBoard/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repo.Models;
using Repo.Advertisements;
using Repo.IRepo;
using Microsoft.AspNet.Identity;
using System.Diagnostics;
using PagedList;
using System.IO;
using System.Drawing;

namespace NoticeBoard.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly IAdvertisementRepo _repo;

        public AdvertisementController(IAdvertisementRepo repo)
        {
            _repo = repo;
        }

        // GET: Advertisement
        public ActionResult Index(int? page, string sortOrder, string searchString)
        {
            var currentPage = page ?? 1;
            int onPage = 15;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "DataDodania" ? "DataDodaniaAsc" : "DataDodania";
            ViewBag.TitleSort = sortOrder == "TytulAsc" ? "Tytul" : "TytulAsc";
            ViewBag.PriceSort = sortOrder == "Cena" ? "CenaAsc" : "Cena";

            var advertisement = _repo.GetAdvetisements();

            switch (sortOrder)
            {
                case "DataDodania":
                    advertisement = advertisement.OrderByDescending(a => a.Date);
                    break;
                case "DataDodaniaAsc":
                    advertisement = advertisement.OrderBy(a => a.Date);
                    break;
                case "Tytul":
                    advertisement = advertisement.OrderByDescending(a => a.Title);
                    break;
                case "TytulAsc":
                    advertisement = advertisement.OrderBy(a => a.Title);
                    break;
                case "Cena":
                    advertisement = advertisement.OrderByDescending(a => a.Price);
                    break;
                case "CenaAsc":
                    advertisement = advertisement.OrderBy(a => a.Price);
                    break;

                default:
                    advertisement = advertisement.OrderByDescending(a => a.Id);
                    break;
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                advertisement = advertisement.Where(s => s.Title.Contains(searchString));
            }

            //advertisement = advertisement.OrderByDescending(adv => adv.Date);
            return View(advertisement.ToPagedList<Advertisement>(currentPage, onPage));

        }

        // GET: Advertisement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = _repo.GetAdvertisementById((int)id);
            var image = advertisement.AdvertisementImage;
            var imageList = new List<string>();
            foreach (var item in image)
            {
                var img = Convert.ToBase64String(item.Image);
                string imageToView = string.Format("data:image/png;base64,{0}", img);
                imageList.Add(imageToView);
            }
            ViewBag.Images = imageList;

            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }


        //// GET: Advertisement/Create
        public ActionResult Create()
        {
            return View();
        }

        public int GenerateNewAdvertisementId()
        {
            int newId = Convert.ToInt32(DateTime.Now.ToString("yyddHHmmss"));
            return newId;
        }
        //// POST: Advertisement/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize] //tylko dla zalogowanych
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Description,Title,Price")] Advertisement advertisement, IEnumerable<HttpPostedFileBase> ImageFile)
        {
            if (ModelState.IsValid)
            {
                //advertisement.Id = GenerateNewAdvertisementId();
                advertisement.UserId = User.Identity.GetUserId();
                advertisement.Date = DateTime.Now;

                foreach (var item in ImageFile)
                {
                    if (item != null && item.ContentLength > 0)
                    {
                        var image = new AdvertisementImage
                        {
                            //AdvertidementId = advertisement.Id,
                        };

                        using (var reader = new BinaryReader(item.InputStream))
                        {
                            image.Image = reader.ReadBytes(item.ContentLength);
                        }
                        advertisement.AdvertisementImage.Add(image);
                    }
                }
               
                try
                {
                    _repo.AddAdvetisement(advertisement);
                    _repo.SaveChanges();
                    return RedirectToAction("MyAdvertisements");
                }
                catch (Exception)
                {
                    return View(advertisement);
                }
            }

            return View(advertisement);
        }

        [Authorize]
        //// GET: Advertisement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = _repo.GetAdvertisementById((int)id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            else if (advertisement.UserId != User.Identity.GetUserId() && !(User.IsInRole("Admin") || User.IsInRole("Moderator")))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(advertisement);
        }

        //// POST: Advertisement/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Title,Date,UserId,Price")] Advertisement advertisement)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repo.UpdateAdvertisement(advertisement);
                    _repo.SaveChanges();
                }
                catch (Exception)
                {
                    ViewBag.Error = true;
                    return View(advertisement);
                }
                // return RedirectToAction("Index");
            }
            ViewBag.Error = false;
            return View(advertisement);
        }

        [Authorize]
        //// GET: Advertisement/Delete/5
        public ActionResult Delete(int? id, bool? error)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = _repo.GetAdvertisementById((int)id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            else if (advertisement.UserId != User.Identity.GetUserId() && !User.IsInRole("Admin"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (error != null)
            {
                ViewBag.Error = true;
            }
            return View(advertisement);
        }

        //// POST: Advertisement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //_repo.DeleteAllImageFromAdvertisement(id);
            _repo.DeleteAdvertisement(id);

            try
            {
                _repo.SaveChanges();
            }
            catch (Exception)
            {

                return RedirectToAction("Delete", new { id = id, error = true });
            }
            return RedirectToAction("MyAdvertisements");
        }

        public ActionResult MyAdvertisements(int? page)
        {
            var currentPage = page ?? 1;
            int onPage = 15;
            string userId = User.Identity.GetUserId();

            var advertisements = _repo.GetAdvetisements();
            advertisements = advertisements.OrderByDescending(d => d.Date).Where(u => u.UserId == userId);

            //foreach (var item in advertisements)
            //{
            //    //var advertisementId = item.Id;

            //    //var getAdvByid = _repo.GetAdvertisementById(advertisementId);
            //    //var images = getAdvByid.AdvertisementImage;
            //    string imageToView = null;
            //    if (item.AdvertisementImage.Count > 0)
            //    {
            //        foreach (var image in item.AdvertisementImage)
            //        {
            //            var img = Convert.ToBase64String(image.Image);
            //            imageToView = string.Format("data:image/png;base64,{0}", img);
            //            ViewBag.ThumbImgAdv = imageToView;
            //        }
            //    }
            //    else
            //    {
            //        //imageToView = null;
            //        ViewBag.ThumbImgAdv = imageToView;
            //    }
            //}

            /*
            var adv = _repo.GetAdvertisementById(1221);

            var image = adv.AdvertisementImage;
            foreach (var item in image)
            {

NoticeBoard/Views/Advertisement/Create.cshtml
@model Repo.Models.Advertisement

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj ogłoszenie</h2>


@using (Html.BeginForm("Create", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                @Html.Label("Zdjęcie", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="ImageFile" type="file" id="ImageFile" multiple/>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Dodaj ogłoszenie" class="btn btn-default" />
                </div>
            </div>
        }
        @*<div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<form id="formTest" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    @Html.LabelFor(model => model.AdvertisementImage, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <span class="btn btn-default btn-file"><span>Dodaj zdjęcia . . .</span><input type="file" name="fileUpload" id="file" multiple /></span>
                        <span class="fileinput-filename"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Dodaj" class="btn btn-success" />
                    </div>
                </div>
            </form>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.AdvertisementImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <span class="btn btn-default btn-file"><span>Dodaj zdjęcia . . .</span><input type="file" name="file" multiple /></span>
                    <span class="fileinput-filename"></span><span class="fileinput-new">Nie wybrano plików</span>
                </div>
            </div>*@
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index", null, new { @class = "btn btn-warning" })
</div>

@section Scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script >
    @*<script>
            $(document).ready(function(){
                $('#btnUpload').click(function () {

                    // Checking whether FormData is available in browser
                    if (window.FormData !== undefined) {

                        var fileUpload = $("#fileUpload").get(0);
                        var files = fileUpload.files;

                        // Create FormData object
                        var fileData = new FormData();

                        // Looping over all files and add it to FormData object
                        for (var i = 0; i < files.length; i++) {
                            fileData.append(files[i].name, files[i]);
                        }

                        // Adding one more key to FormData object
                        //fileData.append('username', ‘Manas’);

                        $.ajax({
                            url: '/Advertisement/Create',
                            type: "POST",
                            contentType: false, // Not to set any content header
                            processData: false, // Not to process data
                            data: fileData,
                            success: function (result) {
                                alert(result);
                            },
                            error: function (err) {
                                alert(err.statusText);
                            }
                        });
                    } else {
                        alert("FormData is not supported.");
                    }
                });
            });
            </script>*@

NoticeBoard/Views/Advertisement/Delete.cshtml
@model Repo.Models.Advertisement

@{
    ViewBag.Title = "Usuwanie";
}

<h2>Usuwanie</h2>
@if (ViewBag.Error == true)
{
    <div class="alert alert-danger" role="alert">
        Wystąpił błąd podczas usuwania !
        Odśwież stronę i spróbuj ponownie.
    </div>
}
<h3>Czy na pewno chcesz usunąć ogłoszenie ?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input id="buttonDeleteInDetails" type="submit" value="Usuń" class="btn btn-default confirmation-alert" />
            @Html.ActionLink("Powrót", "Index", null, new { @class = "btn btn-warning" })
        </div>
    }
</div>
@section Scripts{
    <script type="text/javascript">
        $('.confirmation-alert').on('click', function () {
            return confirm('Czy na pewno chcesz usunąć ?');
        });
    </script>
}

NoticeBoard/Views/Advertisement/Details.cshtml
@model Repo.Models.Advertisement

@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły ogłoszenia</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>
        <dd>
            @foreach (var item in ViewBag.Images)
            {
                <img src="@item" width="300" height="300" />
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Powrót", "Index", null, new { @class = "btn btn-warning" })

    @if(User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Moderator") || Model.UserId == User.Identity.GetUserId()))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @:       
        @Html.ActionLink("Usuń", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
    }
</p>

NoticeBoard/Views/Advertisement/Edit.cshtml
@model Repo.Models.Advertisement

@{
    ViewBag.Title = "Edytuj ogłoszenie";
    ViewBag.Description = "Edytujesz ogłosznie: " + Model.Title;
}

<h2>@ViewBag.Description</h2>
@if(ViewBag.Error == true)
{
    <div class="alert alert-danger" role="alert">
        Wystąpił błąd podczas zapisywania zmian
        Odśwież stronę i spróbuj ponownie !
    </div>
}
else if (ViewBag.Error == false)
{
    <div class="alert alert-success" role="alert">
        Pomyślnie zapisano zmiany !
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @Html.HiddenFor(m => m.Date)
        @Html.HiddenFor(m => m.UserId)


        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <span class="btn btn-default btn-file"><span>Dodaj zdjęcia</span><input type="file" multiple/></span>
                <span class="fileinput-filename"></span><span class="fileinput-new"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index", null, new { @class = "btn btn-warning" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NoticeBoard/Views/Advertisement/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<Repo.Models.Advertisement>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Lista ogłoszeń";
    ViewBag.Description = "Lista ogłoszeń";
    ViewBag.KeyWords = "Lista, ogłoszeń, tablica, ogłoszen";


}
<style>
    img.resize {
        max-width: 200px;
        max-height: 200px;
    }
</style>
<h2>Lista ogłoszeń</h2>
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Dodaj ogłoszenie", "Create", null, new { @class = "btn btn-success" })
}


@using (Html.BeginForm())
{
    <p>
        Wyszukaj: @Html.TextBox("SearchString")
        <input type="submit" value="Wyszukaj" />
    </p>
}

<table class="table">
    <tr>
        <th>
            Zdjęcie
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Description)
        </th>
        <th>
            @Html.ActionLink("Data dodania", "Index", new { sortOrder = ViewBag.DateSort })
        </th>
        <th>
            @Html.ActionLink("Cena", "Index", new { sortOrder = ViewBag.PriceSort })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    var images = item.AdvertisementImage;
                    string imageInItem;
                    foreach (var img in images)
                    {
                        imageInItem = System.Convert.ToBase64String(img.Image);
                        <img class="resize" src="data:image;base64,@imageInItem" />
                        break;
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <div id="buttonGroupInAdvList" class="btn-group">
                    @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || (User.IsInRole("Moderator"))))
                    {
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                        if (User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                        }
                    }

                    @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                </div>
            </td>
        </tr>
                    }

</table>
<div>
    <br />
    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))
</div>

NoticeBoard/Views/Advertisement/MyAdvertisements.cshtml
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity;

@model PagedList.IPagedList<Repo.Models.Advertisement>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Moje ogłoszenia";
}

<h2>Lista moich ogłoszeń</h2>
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Dodaj ogłoszenie", "Create", null, new { @class = "btn btn-success" })
}

    @*@using (Html.BeginForm())
        {
            <p>
                Wyszukaj: @Html.TextBox("SearchString")
                <input type="submit" value="Wyszukaj" />
            </p>
        }*@

    <table class="table">
        <tr>
            <th>
                Zdjęcie
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Description)
            </th>
            <th>
                @Html.ActionLink("Data dodania", "Index", new { sortOrder = ViewBag.DateSort })
            </th>
            <th>
                @Html.ActionLink("Cena", "Index", new { sortOrder = ViewBag.PriceSort })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{
                        var images = item.AdvertisementImage;
                        string imageInItem;
                        foreach (var img in images)
                        {
                            imageInItem = System.Convert.ToBase64String(img.Image);
                            <img class="resize" src="data:image;base64,@imageInItem" />
                            break;
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <div id="buttonGroupInAdvList" class="btn-group">
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || (User.IsInRole("Moderator"))))
                        {
                            @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                            if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                            }
                        }

                        @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                    </div>
                </td>
            </tr>
                        }

    </table>
    <div>
        <br />
        Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("MyAdvertisements", new { page, sortOrder = ViewBag.CurrentSort }))
    </div>